discord:
  token: 'TOKEN'
  messages:
    chat_message: '<username>: <message>'
    join_message: '**<username> joined <server>**'
    leave_message: '**<username> left <server>**'
    disconnect_message: '**<username> was disconnected**'
    server_switch_message: '**<username> moved from <previous_server> to <server>**'
    shutdown_message: '**Proxy shutting down**'
    start_message: '**Ready for connections**'
  webhook:
    avatar_url: 'https://crafatar.com/renders/head/<uuid>?overlay'
    username: '<username>'
    message: '<message>'
  show_bot_messages: false
  show_attachments_ingame: true
  show_activity: true
  # Available placeholders: <amount>
  activity_text: 'with <amount> players online'
  enable_mentions: true
  enable_everyone_and_here: false
  prefer_webhook: true
# Available placeholders: <message> <username> <nickname>
minecraft:
  # Additional placeholders: <discord_format> <username_format> <attachments>
  format: '<discord_format> <reply_format><username_format> <dark_gray>» <reset><message><attachments>'
  discord_format: '<dark_gray>(<color:#7289da>discord<dark_gray>)<reset>'
  username_format: '<color:<role_color>><hover:show_text:<username>><nickname></hover><reset>'
  mention_format: '<color:<role_color>><underlined>@<nickname></underlined></color>'
  reply_format: '<dark_gray><click:open_url:<reply_url>>[<color:#4abdff>←<color:<reply_role_color>><hover:show_text:<reply_username>><reply_nickname></hover><dark_gray>]</click><reset> '
  # Additional placeholders: <attachment_url>
  attachment_format: '<dark_gray><click:open_url:<attachment_url>>[<color:#4abdff>Attachment<dark_gray>]</click><reset>'
channels:
  -   name: 'carbon:global'
      enabled: true
      broadcast_events: true
      discord:
        # Available placeholders: <uuid> <username>
        webhook:
          url: 'WEBHOOK_URL'
        channel_id: 'CHANNEL_ID'
  -   name: 'carbon:staff'
      enabled: true
      minecraft:
        format: '<discord_format> <gray>✦</gray> <username_format> <dark_gray>» <aqua><message><attachments>'
      discord:
        # Available placeholders: <uuid> <username>
        webhook:
          url: 'WEBHOOK_URL'
        channel_id: 'CHANNEL_ID'
